PruebaEfeccty/Controllers/FormularioController.cs
using Azure;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PruebaEfeccty.Data;
using PruebaEfeccty.Models;
using System.Diagnostics;
using System.Linq;

namespace PruebaEfeccty.Controllers
{
    public class FormularioController : Controller
    {
        private readonly ILogger<FormularioController> _logger;
        private readonly ApplicationDbContext _context;

        public FormularioController(ILogger<FormularioController> logger , ApplicationDbContext context)
        {
            _context = context;
            _logger = logger;
        }

        public IActionResult Index()
        {
            List<Formulario> forms = new List<Formulario>();
            forms = _context.Formulario.Include(f=>f.Tipo_Identificacionmodel).ToList();
            return View(forms);
        }
        public IActionResult Data()
        {
            List<Formulario> forms = new List<Formulario>();
            forms = _context.Formulario.Include(f => f.Tipo_Identificacionmodel).ToList();
            return View(forms);
        }
        public List<Tipo_Identificacion> Tipo_Identificacion()
        {
            List<Tipo_Identificacion> forms = new List<Tipo_Identificacion>();
            forms = _context.Tipo_Identificacion.ToList();
            return forms;
        }
        [HttpPost]
        public JsonResult Create([FromBody] Formulario Formulario)
        {
            var eventId = Guid.NewGuid().ToString();
            try
            {
                var response = new Response
                {
                    IsSuccess = true,
                    Result = null,
                    Message = "Guardar"
                };

                
                var model = _context.Formulario.Add(Formulario);
                _context.SaveChanges();
                     
                return Json(response);
            }
            catch (Exception ex)
            {
                var response = new Response
                {
                    IsSuccess = true,
                    Result = null,
                    Message = "error al guardar" + ex.Message
                };
                return Json(response);
            }
        }

        [HttpGet]
        public JsonResult Edit(int id)
        {
            try
            {
                Formulario model = _context.Formulario.Where(f=> f.Id == id).First();

                var response = new Response
                {
                    IsSuccess = true,
                    Result = model
                };
                return Json(response);
            }
            catch (Exception ex)
            {
                var response = new Response
                {
                    IsSuccess = false,
                    Result = null,
                    Message = "error"
                };
                return Json(response);
            }
        }

        [HttpPost]
        public JsonResult Edit([FromBody] Formulario Formulario)
        {
            var eventId = Guid.NewGuid().ToString();
            try
            {
                var response = new Response
                {
                    IsSuccess = true,
                    Result = null,
                    Message = "modificar"
                };

                
                    var model = _context.Formulario.Update(Formulario);
                    _context.SaveChanges();
                    if (model == null)
                    {
                        response.IsSuccess = false;
                        response.Message = "Error";
                    }
               
                return Json(response);
            }
            catch (Exception ex)
            {
                var response = new Response
                {
                    IsSuccess = true,
                    Result = null,
                    Message = "error"
                };
                return Json(response);
            }
        }

        
        [HttpGet]
        public JsonResult Delete(int id)
        {
            var eventId = Guid.NewGuid().ToString();
            try
            {
                var response = new Response
                {
                    IsSuccess = true,
                    Result = null,
                    Message = "eliminar"
                };

                var model = _context.Formulario.Where(f => f.Id == id).First();
                if (model == null)
                {
                    response.IsSuccess = false;
                    response.Message = "error";
                }
                else
                {
                    _context.Formulario.Remove(model);
                    _context.SaveChanges();
                }

                return Json(response);
            }
            catch (Exception ex)
            {
                var response = new Response
                {
                    IsSuccess = true,
                    Result = null,
                    Message = "error" + ex.Message
                };
                return Json(response);
            }
        }
    }
    public class Response
    {
        public bool IsSuccess { get; set; }
        public string Message { get; set; }
        public string Redirect { get; set; }
        public object Result { get; set; }
        public IQueryable<object> ListResult { get; set; }
    }
}

PruebaEfeccty/Controllers/Tipo_IdentificacionController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PruebaEfeccty.Data;
using PruebaEfeccty.Models;
using System.Diagnostics;

namespace PruebaEfeccty.Controllers
{
    public class Tipo_IdentificacionController : Controller
    {
        private readonly ILogger<Tipo_IdentificacionController> _logger;
        private readonly ApplicationDbContext _context;

        public Tipo_IdentificacionController(ILogger<Tipo_IdentificacionController> logger, ApplicationDbContext context)
        {
            _logger = logger;
            _context = context;
        }

        public IActionResult Index()
        {
            List<Tipo_Identificacion> tipos = new List<Tipo_Identificacion>();
            tipos = _context.Tipo_Identificacion.ToList();
            return View(tipos);
        }
        public IActionResult Data()
        {
            List<Tipo_Identificacion> tipos = new List<Tipo_Identificacion>();
            tipos = _context.Tipo_Identificacion.ToList();
            return View(tipos);
        }
        [HttpPost]
        public JsonResult Create([FromBody] Tipo_Identificacion Tipo_Identificacion)
        {
            var eventId = Guid.NewGuid().ToString();
            try
            {
                var response = new Response
                {
                    IsSuccess = true,
                    Result = null,
                    Message = "Guardar"
                };


                var model = _context.Tipo_Identificacion.Add(Tipo_Identificacion);
                _context.SaveChanges();

                return Json(response);
            }
            catch (Exception ex)
            {
                var response = new Response
                {
                    IsSuccess = true,
                    Result = null,
                    Message = "error al guardar" + ex.Message
                };
                return Json(response);
            }
        }

        [HttpGet]
        public JsonResult Edit(int id)
        {
            try
            {
                Tipo_Identificacion model = _context.Tipo_Identificacion.Where(f => f.Id == id).First();

                var response = new Response
                {
                    IsSuccess = true,
                    Result = model
                };
                return Json(response);
            }
            catch (Exception ex)
            {
                var response = new Response
                {
                    IsSuccess = false,
                    Result = null,
                    Message = "error"
                };
                return Json(response);
            }
        }

        [HttpPost]
        public JsonResult Edit([FromBody] Tipo_Identificacion Tipo_Identificacion)
        {
            var eventId = Guid.NewGuid().ToString();
            try
            {
                var response = new Response
                {
                    IsSuccess = true,
                    Result = null,
                    Message = "modificar"
                };


                var model = _context.Tipo_Identificacion.Update(Tipo_Identificacion);
                _context.SaveChanges();
                if (model == null)
                {
                    response.IsSuccess = false;
                    response.Message = "Error";
                }

                return Json(response);
            }
            catch (Exception ex)
            {
                var response = new Response
                {
                    IsSuccess = true,
                    Result = null,
                    Message = "error"
                };
                return Json(response);
            }
        }


        [HttpGet]
        public JsonResult Delete(int id)
        {
            var eventId = Guid.NewGuid().ToString();
            try
            {
                var response = new Response
                {
                    IsSuccess = true,
                    Result = null,
                    Message = "eliminar"
                };

                var model = _context.Tipo_Identificacion.Where(f => f.Id == id).First();
                if (model == null)
                {
                    response.IsSuccess = false;
                    response.Message = "error";
                }
                else
                {
                    _context.Tipo_Identificacion.Remove(model);
                    _context.SaveChanges();
                }

                return Json(response);
            }
            catch (Exception ex)
            {
                var response = new Response
                {
                    IsSuccess = true,
                    Result = null,
                    Message = "error" + ex.Message
                };
                return Json(response);
            }
        }
    }
}

PruebaEfeccty/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PruebaEfeccty</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PruebaEfeccty.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PruebaEfeccty</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Formulario" asp-action="Index">Formulario</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tipo_Identificacion" asp-action="Index">Tipo de Identificación</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - PruebaEfeccty - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>